import type { Metadata } from 'next';
import type { ReactNode } from 'react';
import { Nunito_Sans } from 'next/font/google';
import './globals.css';
import Logo from '@/components/logo';
import Navbar from '@/components/navbar';
import Breadcrumb from '@/components/breadcrumb';
import Sidebar from '@/components/sidebar';
import Footer from '@/components/footer';

const nunito = Nunito_Sans({
  subsets: ['latin'],
  fallback: ['sans_serif'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{ children: ReactNode }>) {
  return (
    <html lang="ro">
      <body className={`${nunito.className}`}>
        <div
          id="top"
          className="fixed inset-x-0 top-0 z-10 bg-white border-b border-gray-950/5"
        >
          <div className="flex h-14 items-center justify-between gap-8 px-2 sm:px-6">
            <Logo />
            <Navbar></Navbar>
          </div>
          <Breadcrumb />
        </div>
        <div
          id="wrapper"
          className="grid min-h-dvh grid-cols-1 grid-rows-[1fr_1px_auto_1px_auto] pt-26.25 lg:grid-cols-[auto_2.5rem_minmax(0,1fr)_2.5rem] lg:pt-14.25"
        >
          <Sidebar />
          <div className="spacer-1"></div>
          <div
            id="main"
            className="row-start-1 lg:col-start-3 md:max-w-5xl p-4"
          >
            {/* <div>Hello from Root layout</div> */}
            {children}
          </div>
          <div className="spacer-2"></div>
          <div className="spacer-horizontal"></div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
